apiVersion: v1
kind: Namespace
metadata:
  name: microservices
  labels:
    name: microservices
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: microservices-staging
  labels:
    name: microservices-staging
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    environment: production
